# Generated by Django 5.0.3 on 2024-03-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_specialtyservices_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ManyToManyField(to='api.specialtyservices'),
        ),
    ]
