# Generated by Django 5.0.3 on 2024-03-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_appointment_service_appointment_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.specialtyservices'),
            preserve_default=False,
        ),
    ]
