# Generated by Django 5.0.3 on 2024-03-27 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_appointment_appointment_time_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='appointment',
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment', to='api.schedule'),
        ),
    ]
