# Generated by Django 5.0.3 on 2024-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_schedule_appointment_appointment_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='patient',
        ),
    ]
