# Generated by Django 5.0.3 on 2024-03-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appointment_rating_alter_appointment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='rating_set',
            field=models.BooleanField(default=False),
        ),
    ]
